"""increase psn token column size

Revision ID: 0d0219d8a35b
Revises: 5bc290fc6c3f
Create Date: 2026-04-30 22:12:50.397150

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0d0219d8a35b'
down_revision: Union[str, None] = '5bc290fc6c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psn_tokens', 'access_token',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=4000),
               existing_nullable=False)
    op.alter_column('psn_tokens', 'refresh_token',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=4000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psn_tokens', 'refresh_token',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    op.alter_column('psn_tokens', 'access_token',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###
