"""add sort_order to achievements

Revision ID: 1166c332f1d4
Revises: 6160e1569978
Create Date: 2026-05-12 06:24:56.833209

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1166c332f1d4'
down_revision: Union[str, None] = '6160e1569978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
