"""add gamerscore_total to trophy_sets

Revision ID: 334befa42d2d
Revises: e5eda9b5f408
Create Date: 2026-05-10 01:00:37.960854

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '334befa42d2d'
down_revision: Union[str, None] = 'e5eda9b5f408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trophy_sets', sa.Column('gamerscore_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trophy_sets', 'gamerscore_total')
    # ### end Alembic commands ###
