"""add icon_url to achievements

Revision ID: 43b0d58c859e
Revises: 6657020f5036
Create Date: 2026-04-27 22:10:41.431579

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '43b0d58c859e'
down_revision: Union[str, None] = '6657020f5036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('icon_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'icon_url')
    # ### end Alembic commands ###
