"""add psn_tokens table

Revision ID: 5bc290fc6c3f
Revises: 03647177f394
Create Date: 2026-04-30 22:02:44.040536

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5bc290fc6c3f'
down_revision: Union[str, None] = '03647177f394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
