"""add trophy sets

Revision ID: 6657020f5036
Revises: a72551209ff7
Create Date: 2026-04-23 20:35:32.021864

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6657020f5036'
down_revision: Union[str, None] = 'a72551209ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trophy_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform_communication_id', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('achievements', sa.Column('trophy_set_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'achievements', 'trophy_sets', ['trophy_set_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'trophy_set_id')
    op.drop_table('trophy_sets')
    # ### end Alembic commands ###
