"""add gamerscore_total to trophy_sets

Revision ID: 6c2df5630d86
Revises: 334befa42d2d
Create Date: 2026-05-10 21:21:12.593236

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6c2df5630d86'
down_revision: Union[str, None] = '334befa42d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
