"""add icon_url to achievements

Revision ID: 986daa9286ab
Revises: 43b0d58c859e
Create Date: 2026-04-27 22:12:52.122312

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '986daa9286ab'
down_revision: Union[str, None] = '43b0d58c859e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
