"""add psn_account_id to users

Revision ID: a9d49294645b
Revises: a54759221c87
Create Date: 2026-04-27 23:15:24.919704

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a9d49294645b'
down_revision: Union[str, None] = 'a54759221c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('psn_account_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'psn_account_id')
    # ### end Alembic commands ###
