"""add xbox_tokens table

Revision ID: e5eda9b5f408
Revises: 0d0219d8a35b
Create Date: 2026-05-06 05:01:55.402134

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e5eda9b5f408'
down_revision: Union[str, None] = '0d0219d8a35b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
